<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\Application\Application.csproj" />
    <ProjectReference Include="..\TD_Project.Contracts\TD_Project.Contracts.csproj" />
  </ItemGroup>

</Project>
