<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Ronda2</AssemblyName>
    <RootNamespace>TD_Project.Exploration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\EstrategiaTresMosqueteros.cs" />
    <Compile Include="..\EstrategiaMhiMayoria.cs" />
    <ProjectReference Include="..\..\src\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\src\Application\Application.csproj" />
  </ItemGroup>

</Project>
